export enum NotificationType {
  WATERING_REMINDER = 'WATERING_REMINDER',
  HELP_REQUEST = 'HELP_REQUEST',
  HELP_RESPONSE = 'HELP_RESPONSE',
  POST_LIKE = 'POST_LIKE',
  POST_COMMENT = 'POST_COMMENT',
  WEATHER_ALERT = 'WEATHER_ALERT',
  SYSTEM_UPDATE = 'SYSTEM_UPDATE'
}